#! /usr/bin/env python
#
#   Copyright (C) 2012 Ash (Tuxdude)
#   tuxdude.github@gmail.com
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import sys
from ArgParser import ArgParser
from RepoConfigParser import RepoConfigParser, RepoConfigParserError

# XXX: Commenting arg parser till we have XML parsing working
#argParser = ArgParser()
#argParser.Parse()

repoConfigParser = RepoConfigParser()
try:
    repoConfigParser.Parse(sys.argv[1])
except RepoConfigParserError as err:
    print err

sys.exit(0)
